name: readdy2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blosc=1.21.5=hc2324a3_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - h5py=3.7.0=nompi_py39h817c9c5_102
  - hdf5=1.12.2=nompi_h4df4325_101
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libcurl=8.7.1=hca28451_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=hc881cc4_6
  - libgfortran-ng=13.2.0=h69a702a_6
  - libgfortran5=13.2.0=h43f5ff8_6
  - libgomp=13.2.0=hc881cc4_6
  - liblapack=3.9.0=22_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h95c4c6d_6
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - ncurses=6.4.20240210=h59595ed_0
  - openssl=3.2.1=hd590300_1
  - pint=0.23=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.9.19=h0755675_0_cpython
  - python_abi=3.9=4_cp39
  - readdy=2.0.12=py39h8b9aba8_1
  - readline=8.2=h8228510_1
  - setuptools=69.5.1=pyhd8ed1ab_0
  - snappy=1.2.0=hdb0a2a9_1
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
    - anyio==4.3.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - botorch==0.10.0
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - comm==0.2.2
    - contourpy==1.2.1
    - cycler==0.12.1
    - debugpy==1.8.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - filelock==3.17.0
    - fonttools==4.51.0
    - fqdn==1.5.1
    - fsspec==2024.12.0
    - gpytorch==1.11
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - idna==3.7
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.0
    - ipykernel==6.29.4
    - ipython==8.18.1
    - isoduration==20.11.0
    - jaxtyping==0.2.36
    - jedi==0.19.1
    - jinja2==3.1.3
    - joblib==1.4.0
    - json5==0.9.25
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.1
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.1.6
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.1
    - kiwisolver==1.4.5
    - linear-operator==0.5.1
    - markupsafe==2.1.5
    - matplotlib==3.8.4
    - matplotlib-inline==0.1.7
    - mistune==3.0.2
    - mpmath==1.3.0
    - multipledispatch==1.0.0
    - nbclient==0.10.0
    - nbconvert==7.16.3
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - notebook==7.1.3
    - notebook-shim==0.2.4
    - numpy==1.23.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - opt-einsum==3.4.0
    - overrides==7.7.0
    - packaging==24.0
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==10.3.0
    - platformdirs==4.2.1
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.22
    - pygments==2.17.2
    - pyparsing==3.1.2
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==26.0.2
    - referencing==0.35.0
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.18.0
    - scikit-learn==1.4.2
    - scipy==1.13.0
    - send2trash==1.8.3
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - sympy==1.13.1
    - terminado==0.18.1
    - threadpoolctl==3.4.0
    - tinycss2==1.3.0
    - tomli==2.0.1
    - torch==2.5.1
    - tornado==6.4
    - traitlets==5.14.3
    - triton==3.1.0
    - typeguard==2.13.3
    - types-python-dateutil==2.9.0.20240316
    - tzdata==2024.1
    - uri-template==1.3.0
    - urllib3==2.2.1
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - zipp==3.18.1
prefix: /home/xenia/miniconda3/envs/readdy2
